version: '3.8'

services:
  # Backend Laravel
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: ponylink_backend
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=ponylink
      - DB_USERNAME=postgres
      - DB_PASSWORD=1234
      - APP_ENV=production
      - APP_DEBUG=false
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./backend/storage/app/public:/var/www/html/public/storage
    networks:
      - ponylink_network
    depends_on:
      - db
    command: bash -c "php artisan migrate --force && apache2-foreground"

  # Frontend Vue
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ponylink_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - ponylink_network

  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: ponylink_db
    environment:
      - POSTGRES_DB=ponylink
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ponylink_network

networks:
  ponylink_network:
    driver: bridge

volumes:
  postgres_data:
